apiVersion: v1
kind: Secret
metadata:
  name: confine-secrets
type: Opaque
stringData:
  DB_PASS: postgres
  JWT_SECRET_KEY: change-me
  OPENROUTER_APIKEY: change-me
  OPENROUTER_MODEL: change-me
  MUSIXMATCH_APIKEY: change-me
  SENTRY_DSN: ""